# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-aldomann-github-io-blog'

# google-ID: 'UA-112060364-1'

menu:
- {name: 'About Me', path: 'menu', url: '../../'}
- {name: 'Tech Stuff', path: 'menu', url: 'tech'}
- {name: 'Design', path: 'menu', url: 'design'}
- {name: 'Tags', path: 'menu', url: '../tags'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'google-plus', link: 'https://plus.google.com/u/0/+AlfredoHernándezC'}
- {icon: 'github', link: 'https://www.github.com/aldomann'}
# - {icon: 'twitter', link: 'https://twitter.com/aldomann'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/aldomann'}
- {icon: 'telegram', link: 'https://telegram.me/aldomann'}
- {icon: 'envelope', link: 'mailto:aldomann.designs@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
